name: app_color
description: Collection of color with advanced controlling system.
version: 0.0.4
repository: https://github.com/P-YMR/flutter_colors.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: