name: app_color
description: Collection of color with advanced controlling system.
version: 0.0.3
repository: https://github.com/P-YMR/flutter_colors.git
homepage: https://github.com/P-YMR/flutter_colors/blob/d8d4ed8fb5170165aa00f2f3e94ead99ebe4e5ad/lib/app_color.dart

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: