name: app_color
description: Collection of color with advanced controlling system.
version: 1.0.5
repository: https://github.com/Mohiuddin655-PUB/flutter_app_color

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true